spring.application.name=splitShare

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://ticketwave-mysql-ticketwave.c.aivencloud.com:20817/splitshare?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

jwt.secret=SplitWiseSecretKeyForJWTAuthentication2026SplitWiseSecretKey
jwt.expiration=86400000